### ISSUE TITLE
Формичката за пускане тикет чупи лейаута

### ISSUE THREAD

**Issue by ivominchev** [orbisius/orbisius-support-tickets#1]
Формичката за пускане тикет чупи лейаута. Изхвърля сайдбара надолу.
https://pctehnik.com/zapitvaniya/izprati-zapitvane/

**Comment by lordspace** [comment]
Оправих го. Ще пусна версия. Правя подобрения, когато човекът не е логнат.
Оказа се, че трябва по друг начин да направя защитата с парола. WP не позволява да се кометират постове, когато имат парола ?!?
