### ISSUE TITLE
Проблеми при създаване на тикет без акаунт

### ISSUE THREAD

**Issue by ivominchev** [orbisius/orbisius-support-tickets#2]
1. Създадох тикет без акаунт, като използвах един мой мейл в abv.bg, който ползвам за "черна" работа. Не получих нищо там, както и на моя служебен мейл. 
2. Реално, ако съм потребител, който иска да пусне тикет без акаунт, изписва ми ID на тикета при фибнализирането му и дотам. Ако не се съобразя да го запиша някъде - губя. 
Освен това във "View ticket"ми липсва, ако не е въведено ID дава "Invalid ticket. Вместо това, би било добре да има input за Ticket ID и Pass, които да те отведат то желания тикет.

**Comment by lordspace** [comment]
сега в новата версия има подобрения относно публиуването на тикет без да си логнат

**Comment by ivominchev** [comment]
Аз мислех, че 1.03 е новата, защото последно ползвах 1.02. 
ОК. Чакам с нетърпение.

**Comment by lordspace** [comment]
Да, точно така. 1.0.3 е новата версия. Кодът в github ще е полу стабилен.
Тествам версията още и я пускам в WordPress.org и ще излезне обновление в WP

**Comment by lordspace** [comment]
Имаш ли много тикети регистрирани?
Правя едни промени и отговорите на старите тикети може да не се покажат.
промяната се налага защото WP има джаджа, която показва последните коментари, а не трябва да се показват отговорите на тикетите като коментари

**Comment by ivominchev** [comment]
Ами аз от Гит я свалих тази сутрин и за нея докладвам този проблем.

**Comment by lordspace** [comment]
от github не е готова още

**Comment by ivominchev** [comment]
Само два тикета имам и те са тестови.  Още не съм пуснал плъгина пъблик.

**Comment by lordspace** [comment]
Оки. Сега проверявам защо зацикля публикуването на отговор при затворен тикет

**Comment by ivominchev** [comment]
> от github не е готова още

Ясно. Хванал съм нефинален пул. :-) Сядам и кротко чакам да стане. Само, моля да ми кажеш, че не знам дали WP ще ми предложи ъпдейт, защото може да види, че съм с 1.03.

**Comment by lordspace** [comment]
в момента преглеждам защо не се пращат имейлите

**Comment by ivominchev** [comment]
OK. Ако искаш като си готов кажи да тествам.

**Comment by lordspace** [comment]
Да, ще пиша, като съм готов.

**Comment by lordspace** [comment]
Ще трябва да го продължа или по-късно или утре.

**Comment by lordspace** [comment]
Много малко остана

**Comment by lordspace** [comment]
Иво, още работя по въпроса

**Comment by ivominchev** [comment]
OK

**Comment by lordspace** [comment]
Иво, тествам ... 😄

**Comment by lordspace** [comment]
Готово. пуснах нова версия.
Можеш да махнеш старата версия, която си инсталирал от github и да ползваш по-стабилната от wordpress directory
